//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_Customer
    {
        public int ID { get; set; }
        public string APP_Customer_ID { get; set; }
        public string Grade_No { get; set; }
        public string Customer_ID { get; set; }
        public string Dealer_ID { get; set; }
        public string Customer_name { get; set; }
        public string Store_name { get; set; }
        public string Pic { get; set; }
        public string Identifier { get; set; }
        public string Personal_ID { get; set; }
        public string Mail_Address { get; set; }
        public string Telm { get; set; }
        public string BCategory_ID { get; set; }
        public string SCategory_ID { get; set; }
        public string Address_zip { get; set; }
        public string Address_City { get; set; }
        public string Address_Zone { get; set; }
        public string Address { get; set; }
        public string Customer_Password { get; set; }
        public string Customer_Checkstr { get; set; }
        public string Use_Bonus { get; set; }
        public Nullable<double> Use_Bonus_Percent { get; set; }
        public string APP_Creditpay_Bank { get; set; }
        public string APP_Creditpay_Fee { get; set; }
        public string APP_Creditpay_Singelpay_Max { get; set; }
        public string APP_Creditpay_Daypay_Max { get; set; }
        public string APP_Creditpay_Monthpay_Max { get; set; }
        public string Request_Payment_Bank { get; set; }
        public string Request_Payment_Branch { get; set; }
        public string Request_Payment_Account_Name { get; set; }
        public string Request_Payment_Account { get; set; }
        public string Statu { get; set; }
        public string Facebook { get; set; }
        public string Line { get; set; }
        public string Istransaction { get; set; }
        public Nullable<System.DateTime> Build_Date { get; set; }
        public string Builder { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Modifier { get; set; }
    }
}
