//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_TCash
    {
        public int ID { get; set; }
        public string Cash_No { get; set; }
        public string APP_Customer_ID { get; set; }
        public string Request_Payment_Bank { get; set; }
        public string Request_Payment_Branch { get; set; }
        public string Request_Payment_Account_Name { get; set; }
        public string Request_Payment_Account { get; set; }
        public string Transfer_Cash { get; set; }
        public Nullable<long> Use_Bonus { get; set; }
        public string ISCheck { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> Build_Date { get; set; }
    }
}
