//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SurPrise_Item
    {
        public int ID { get; set; }
        public string SurItem_No { get; set; }
        public string SurBox_No { get; set; }
        public string System_ID { get; set; }
        public string Serial_Number { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> Creat_Day { get; set; }
    }
}
