//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_Order
    {
        public int ID { get; set; }
        public string APOrder_ID { get; set; }
        public string Order_ID { get; set; }
        public string User_System_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Order_ID { get; set; }
        public string Promotion_ID { get; set; }
        public Nullable<long> Use_Bonus { get; set; }
        public Nullable<long> Return_Bonus { get; set; }
        public string IsInstallment { get; set; }
        public Nullable<int> Installment_Period { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Pay_Amount { get; set; }
        public string Pay_Result { get; set; }
        public string Approve_Code { get; set; }
        public string InvoiceNumber { get; set; }
        public string Goods_Return_Statu { get; set; }
        public Nullable<System.DateTime> Build_Date { get; set; }
    }
}
