//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_Notice
    {
        public int ID { get; set; }
        public string Notice_No { get; set; }
        public string Notice_Type { get; set; }
        public string Notice_Title { get; set; }
        public string Notice_content { get; set; }
        public Nullable<System.DateTime> Notice_Day { get; set; }
        public Nullable<System.DateTime> Creat_Day { get; set; }
        public string IsNotice { get; set; }
    }
}
