//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_Activity
    {
        public int ID { get; set; }
        public string Activity_ID { get; set; }
        public string APP_Customer_ID { get; set; }
        public string Activity_Title { get; set; }
        public string Activity_content { get; set; }
        public string Activity_Pic { get; set; }
        public string Date1 { get; set; }
        public string Date2 { get; set; }
        public string Builder { get; set; }
        public Nullable<System.DateTime> Build_Date { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
