//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GomypayDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_News
    {
        public int ID { get; set; }
        public int News_No { get; set; }
        public string News_Type { get; set; }
        public string News_Title { get; set; }
        public string News_Content { get; set; }
        public string Statu { get; set; }
        public Nullable<System.DateTime> Creat_Day { get; set; }
        public string Builder { get; set; }
        public string Modifier { get; set; }
    }
}
